[package]
name = "rcarve-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
rcarve = { path = "../crates/rcarve" }
iced = { version = "0.13.1", features = ["canvas", "advanced"] }
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ulid = "1.1"
kurbo = "0.12.0"
